server:
  port: 8002
  error:
    include-message: always

spring:
  application:
    name: auth-service
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8671/eureka
  instance:
    hostname: localhost