server:
  port: 8001
  error:
    include-message: always

spring:
  application:
    name: core-service
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8671/eureka
  instance:
    hostname: localhost