server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #routes:
        #- id: core-service
          #uri: lb://core-service
          #predicates:
            #- Path=/demo/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8671/eureka
  instance:
    hostname: localhost